### ISSUE TITLE
Help Language Updates

### ISSUE THREAD

**Issue by JoeDailey** [motocru/role-assignment-bot#4]
I think we can reduce the complexity of the help message.
---
Users can join roles by reacting to a message *you* create. Your message must take the following format, where users can either choose 'one' role or 'any' number of roles. You can edit this message in the future and it will continue to work as expected.
```
@react4role choose (one|any)
1️⃣ @role1
2️⃣ @role2
```
Role assignment messages can only be created by the server owner and will only work in text channels named 'roles' or channels with `@react4role` somewhere in the channel topic. 

---
I think we can remove the help command and just print this for any @react4role mention that isn't the proper format. This also requires adding @react4role back into the choose command. I think this is an improvement for non-admins because the name is also the instruction 'react for role'.

**Comment by motocru** [comment]
changed the help message requirement to the RoleMessageVerification function
role-assignment-bot/bot.js

Lines 34 to 36 in 8533d5f

 if (!RoleMessageVerification(message)) { 
     message.channel.send(config.messages.HELP); 
 } 

added a check for a reference to the bot id in the RoleMessageVerification function to add a requirement to include tagging the bot
role-assignment-bot/bot.js

Line 143 in 8533d5f

 if (!line1[0].toLowerCase().includes(client.user.id)) return false; 

Closing issue
